"""managed on cascade 

Revision ID: 23e9cd3ca3e0
Revises: f6b54a0c1c61
Create Date: 2026-01-21 17:26:12.701025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e9cd3ca3e0'
down_revision: Union[str, Sequence[str], None] = 'f6b54a0c1c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('adminlog_admin_id_fkey'), 'adminlog', type_='foreignkey')
    op.create_foreign_key(None, 'adminlog', 'users', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('brandprofile_user_id_fkey'), 'brandprofile', type_='foreignkey')
    op.create_foreign_key(None, 'brandprofile', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('event', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('event', 'brand_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('event_brand_id_fkey'), 'event', type_='foreignkey')
    op.drop_constraint(op.f('event_user_id_fkey'), 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event', 'brandprofile', ['brand_id'], ['id'], ondelete='CASCADE')
    op.alter_column('eventapplication', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('eventapplication', 'influencer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('eventapplication_influencer_id_fkey'), 'eventapplication', type_='foreignkey')
    op.drop_constraint(op.f('eventapplication_event_id_fkey'), 'eventapplication', type_='foreignkey')
    op.create_foreign_key(None, 'eventapplication', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'eventapplication', 'influencerprofile', ['influencer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('influencerprofile_user_id_fkey'), 'influencerprofile', type_='foreignkey')
    op.create_foreign_key(None, 'influencerprofile', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('message_sender_id_fkey'), 'message', type_='foreignkey')
    op.drop_constraint(op.f('message_receiver_id_fkey'), 'message', type_='foreignkey')
    op.drop_constraint(op.f('message_event_id_fkey'), 'message', type_='foreignkey')
    op.drop_constraint(op.f('message_application_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'message', 'eventapplication', ['application_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notification_user_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('otpmodel_user_id_fkey'), 'otpmodel', type_='foreignkey')
    op.create_foreign_key(None, 'otpmodel', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rating_rater_id_fkey'), 'rating', type_='foreignkey')
    op.drop_constraint(op.f('rating_ratee_id_fkey'), 'rating', type_='foreignkey')
    op.drop_constraint(op.f('rating_event_id_fkey'), 'rating', type_='foreignkey')
    op.create_foreign_key(None, 'rating', 'users', ['rater_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rating', 'users', ['ratee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rating', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sociallink_influencer_profile_id_fkey'), 'sociallink', type_='foreignkey')
    op.create_foreign_key(None, 'sociallink', 'influencerprofile', ['influencer_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sociallink', type_='foreignkey')
    op.create_foreign_key(op.f('sociallink_influencer_profile_id_fkey'), 'sociallink', 'influencerprofile', ['influencer_profile_id'], ['id'])
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.create_foreign_key(op.f('rating_event_id_fkey'), 'rating', 'event', ['event_id'], ['id'])
    op.create_foreign_key(op.f('rating_ratee_id_fkey'), 'rating', 'users', ['ratee_id'], ['id'])
    op.create_foreign_key(op.f('rating_rater_id_fkey'), 'rating', 'users', ['rater_id'], ['id'])
    op.drop_constraint(None, 'otpmodel', type_='foreignkey')
    op.create_foreign_key(op.f('otpmodel_user_id_fkey'), 'otpmodel', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_user_id_fkey'), 'notification', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_application_id_fkey'), 'message', 'eventapplication', ['application_id'], ['id'])
    op.create_foreign_key(op.f('message_event_id_fkey'), 'message', 'event', ['event_id'], ['id'])
    op.create_foreign_key(op.f('message_receiver_id_fkey'), 'message', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(op.f('message_sender_id_fkey'), 'message', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'influencerprofile', type_='foreignkey')
    op.create_foreign_key(op.f('influencerprofile_user_id_fkey'), 'influencerprofile', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'eventapplication', type_='foreignkey')
    op.drop_constraint(None, 'eventapplication', type_='foreignkey')
    op.create_foreign_key(op.f('eventapplication_event_id_fkey'), 'eventapplication', 'event', ['event_id'], ['id'])
    op.create_foreign_key(op.f('eventapplication_influencer_id_fkey'), 'eventapplication', 'influencerprofile', ['influencer_id'], ['id'])
    op.alter_column('eventapplication', 'influencer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('eventapplication', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key(op.f('event_user_id_fkey'), 'event', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('event_brand_id_fkey'), 'event', 'brandprofile', ['brand_id'], ['id'])
    op.alter_column('event', 'brand_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('event', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'brandprofile', type_='foreignkey')
    op.create_foreign_key(op.f('brandprofile_user_id_fkey'), 'brandprofile', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'adminlog', type_='foreignkey')
    op.create_foreign_key(op.f('adminlog_admin_id_fkey'), 'adminlog', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###
