"""added is_delivered

Revision ID: 300962d327f8
Revises: b617c7dbca33
Create Date: 2026-01-19 15:15:12.850770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300962d327f8'
down_revision: Union[str, Sequence[str], None] = 'b617c7dbca33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_delivered', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_delivered')
    # ### end Alembic commands ###
