"""fix message receiver_id nullable and add conversation_id index

Revision ID: 4abfdb0cdf78
Revises: 5ac208e9f5b6
Create Date: 2026-02-26 05:10:16.805817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abfdb0cdf78'
down_revision: Union[str, Sequence[str], None] = '5ac208e9f5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
