"""Add conversations and update messages - no enums

Revision ID: b1808c7c17f5
Revises: d4fb1dde29d7
Create Date: 2026-02-25 10:15:49.357656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1808c7c17f5'
down_revision: Union[str, Sequence[str], None] = 'd4fb1dde29d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False, server_default='DIRECT'),
    sa.Column('participant_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('admin_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('unread_counts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_message_id', sa.Uuid(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.add_column('message', sa.Column('conversation_id', sa.Uuid(), nullable=True))
    op.add_column('message', sa.Column('type', sa.String(), nullable=False, server_default='TEXT'))
    op.add_column('message', sa.Column('read_by', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False))
    op.add_column('message', sa.Column('delivered_to', sa.ARRAY(sa.UUID()), server_default='{}', nullable=False))
    op.add_column('message', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column('message', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'message', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'type')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
