"""managed cascade

Revision ID: f6b54a0c1c61
Revises: 300962d327f8
Create Date: 2026-01-21 15:54:12.296355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b54a0c1c61'
down_revision: Union[str, Sequence[str], None] = '300962d327f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'influencerprofile', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'influencerprofile', type_='unique')
    # ### end Alembic commands ###
